apiVersion: v1
kind: Service
metadata:
  name: monailabel
  labels:
    run: monailabel
spec:
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30900
    protocol: TCP
  type: NodePort
  selector:
    app: monailabel
